In [1]:
import numpy as np

np.random.randint(0,2, size=(5,5))

array([[1, 0, 0, 0, 1],
       [1, 1, 1, 1, 0],
       [0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1]])

In [51]:
arr = np.ones((5,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
zero = np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
zero[1,1] = 9
print(zero)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [56]:
arr[1:4,1:4] = zero
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
