In [63]:
import numpy as np
a = np.array([
    [1,2,3],
    [2,4,6],
])
print(a)

[[1 2 3]
 [2 4 6]]


In [64]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [67]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [69]:
np.full_like(a, 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [70]:
np.random.rand(2,2)

array([[0.4148475 , 0.36570274],
       [0.62948436, 0.6111935 ]])

In [72]:
np.random.randint(0,8, size=(3,3))

array([[4, 6, 4],
       [6, 1, 2],
       [6, 3, 6]])

In [75]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [77]:
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [7]:
import numpy as np

j = np.array([[[10,20,30],[40,50,60]], [[5,10,15],[20,25,30]]], dtype='int16')
print(j)


[[[10 20 30]
  [40 50 60]]

 [[ 5 10 15]
  [20 25 30]]]


In [3]:
j.ndim

3

In [8]:
j.dtype

dtype('int16')

In [9]:
j.itemsize

2

In [10]:
j.size

12

In [11]:
j.nbytes

24

In [12]:
j[0,1]

array([40, 50, 60], dtype=int16)

In [13]:
j[:, 0,1]

array([20, 10], dtype=int16)

In [16]:
np.random.randint(10, size=(3,3))

array([[2, 7, 6],
       [5, 5, 6],
       [6, 6, 4]])

In [17]:
np.random.rand(3,3)

array([[0.71868211, 0.22608491, 0.27207528],
       [0.50342964, 0.84879439, 0.13989479],
       [0.47125379, 0.73242067, 0.12396397]])

In [20]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr = np.array([[1,2,3],[4,5,6]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]
